# Generated by Django 6.0.2 on 2026-03-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_assets', '0004_sharingscope_check_in_virtual_labs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondaEnvironment',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assets.baseasset')),
                ('environment_name', models.CharField(blank=True, max_length=255)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('package_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('base_assets.baseasset',),
        ),
        migrations.CreateModel(
            name='CondaEnvironmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='conda_environments/')),
                ('file_type', models.CharField(choices=[('environment_tar', 'Environment TAR archive'), ('requirements_list', 'Requirements.txt file')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('conda_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conda_environments.condaenvironment')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('conda_environment', 'file_type')},
            },
        ),
    ]
