# Generated by Django 6.0.2 on 2026-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conda_environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condaenvironment',
            name='dependency_list',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='dependency_lists/'),
        ),
        migrations.AddField(
            model_name='condaenvironment',
            name='environment_file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='conda_environments/'),
        ),
        migrations.DeleteModel(
            name='CondaEnvironmentFile',
        ),
    ]
