# Generated by Django 6.0.2 on 2026-04-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conda_environments', '0002_condaenvironment_dependency_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condaenvironment',
            name='dependency_list',
            field=models.FileField(blank=True, null=True, upload_to='dependency_lists/'),
        ),
        migrations.AlterField(
            model_name='condaenvironment',
            name='environment_file',
            field=models.FileField(blank=True, null=True, upload_to='conda_environments/'),
        ),
    ]
